apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity 
metadata:
  name: demo
spec:
  type: 0
  ResourceID: /subscriptions/f921dcc4-9d2c-4b73-a12e-8c3ca091af03/resourcegroups/MC_azds-rg_xiaodong-azds-dev_westus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/demo
  ClientId: eaa35d00-da73-4213-bcaf-988c1735937d
