apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: "demo"
    aadpodidbinding: "demo"
  name: demo
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: demo
        aadpodidbinding: demo
    spec:
      containers:
        - name: demo
          image: "oneesdevacr.azurecr.io/test/demo:latest"
          imagePullPolicy: Always

          args:
            - "--subscriptionid=f921dcc4-9d2c-4b73-a12e-8c3ca091af03"
            - "--clientid=eaa35d00-da73-4213-bcaf-988c1735937d"
            - "--resourcegroup=MC_azds-rg_xiaodong-azds-dev_westus2"
            - "--aad-resourcename=https://vault.azure.net"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
          volumeMounts:
            - name: ca-pemstore
              mountPath: /etc/ssl/certs
              readOnly: false
      imagePullSecrets:
        - name: acr-auth
      volumes:
        - name: ca-pemstore
          configMap:
            name: ca-pemstore
---
apiVersion: v1
kind: Service
metadata:
  name: "demo"
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: "demo"
