apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity 
metadata:
  name: demo 
spec:
  type: 0
  ResourceId: subscriptions/c6f1efb8-906b-437e-99b4-e1f0881ec8d2/resourceGroups/azds-dev-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/demo
  ClientId: 7a359d69-539b-4394-9cea-182684fb268a