kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-reader-rolebinding
  namespace: default
  labels:
    app: demo
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
  namespace: default
roleRef:
  kind: Role
  name: config-reader
  apiGroup: ""