apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity 
metadata:
  name: demo
spec:
  type: 0
  ResourceID: /subscriptions/f921dcc4-9d2c-4b73-a12e-8c3ca091af03/resourcegroups/sace-dev-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/sace-dev-kv-reader
  ClientId: 8388853b-4e49-4421-ad71-2b6684e66580
